# Generated by Django 5.0.4 on 2024-05-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_userevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
